#ifndef DEFINES_H
#define DEFINES_H

#define LABEL_MAX_LENGTH 16
#define DIRECTIVE_MAX_LENGTH 16
#define OPERAND_MAX_LENGTH 8
#define REGISTER_MAX_LENGTH 2
#define STRING_MAX_LENGTH 256

#define MAX_TOKENS_PER_OPERAND 5
#define OPCODE_MAX_LENGTH 4
#endif
